const Eos = require('eosjs');

const jungle = {
  keyProvider: '',
  chainId: '038f4b0fc8ff18a4f0842a8f0564611f6e96e8535901dd45e43ac8691a1c4dca',
  httpEndpoint: 'http://jungle.cryptolions.io:18888'
}
const eos = Eos(jungle);

// const abi = require('./messenger.abi')
eos.setabi('messenger', abi)
  .then(res => console.log('loaded messenger abi'))

export function sendSha () {
  return eos.contract('messenger')
    .then(messenger => {
      console.log(messenger)
      return messenger.sendsha() // add params
    })
}




const abi = {
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-08-31T18:52:39",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "message",
      "base": "",
      "fields": [{
          "name": "msg_id",
          "type": "uint64"
        },{
          "name": "from",
          "type": "name"
        },{
          "name": "to",
          "type": "name"
        },{
          "name": "msg_sha",
          "type": "checksum256"
        }
      ]
    },{
      "name": "sendsha",
      "base": "",
      "fields": [{
          "name": "from",
          "type": "name"
        },{
          "name": "to",
          "type": "name"
        },{
          "name": "msg_id",
          "type": "uint64"
        },{
          "name": "msg_sha",
          "type": "checksum256"
        }
      ]
    },{
      "name": "removemsg",
      "base": "",
      "fields": [{
          "name": "to",
          "type": "name"
        },{
          "name": "msg_id",
          "type": "uint64"
        }
      ]
    },{
      "name": "removesha",
      "base": "",
      "fields": [{
          "name": "msg_sha",
          "type": "checksum256"
        }
      ]
    },{
      "name": "printmsg",
      "base": "",
      "fields": [{
          "name": "other",
          "type": "name"
        }
      ]
    }
  ],
  "actions": [{
      "name": "sendsha",
      "type": "sendsha",
      "ricardian_contract": ""
    },{
      "name": "removemsg",
      "type": "removemsg",
      "ricardian_contract": ""
    },{
      "name": "removesha",
      "type": "removesha",
      "ricardian_contract": ""
    },{
      "name": "printmsg",
      "type": "printmsg",
      "ricardian_contract": ""
    }
  ],
  "tables": [{
      "name": "message",
      "index_type": "i64",
      "key_names": [
        "msg_id"
      ],
      "key_types": [
        "uint64"
      ],
      "type": "message"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
}
